name: ml_session

channels:
  - bioconda
  - conda-forge
  - defaults

dependencies:
  - jupyterlab=4.3.1
  - jupyter=1.1.1
  - matplotlib=3.9.2
  - numpy=2.1.3
  - pandas=2.2.3
  - pip=24.3.1
  - python=3.13.0
  - scikit-learn=1.5.2
